name: default-policy-config
sources:
  - id: policy-source
    type: git
    url: https://github.com/naufalAE/opa-policies
    branch: main
    paths:
      - column_mask.rego
      - batch_mask.rego
      - data_access.rego
      - ../data/data.json
    policy_type: rego
    destination: /
