name: default-policy-config
sources:
  - id: policy-source
    type: git
    url: https://github.com/naufalAE/opa-policies
    branch: main
    paths:
      - data-access.rego
    policy_type: rego
    destination: /
